Updating kinematic: ini files
roboticslab-uc3m/teo-configuration-files pull request #20
Opened 2019-05-06 10:27 UTC by rsantos88

Updating kinematic: ini files

2019-05-06 13:30 UTC, jgvictores commented
@rsantos88 How about removing old/unused/useless?

2019-05-06 13:53 UTC, jgvictores commented
> @rsantos88 How about removing old/unused/useless?

PS: Yes, this was proposed at https://github.com/roboticslab-uc3m/teo-configuration-files/issues/7

2019-05-06 13:53 UTC, jgvictores commented on share/kinematics/leftArmKinematics-fetch.ini
> +link_6 (offset -90.0) (D  0.0    ) (A  0.0     ) (alpha  90.0)
`link_5` and `link_5` redundant with `HN`

2019-05-06 13:54 UTC, jgvictores requested changes

2019-05-06 13:54 UTC, jgvictores commented on share/kinematics/rightArmKinematics-fetch.ini
> +link_6 (offset -90.0) (D  0.0    ) (A  0.0      ) (alpha  90.0)
`link_5` and `link_5` redundant with `HN`

2019-05-07 11:24 UTC, rsantos88 commented
It's already done but, can I close this PR and reopen a new PR with less changes?

2019-05-07 13:16 UTC, closed without merging

2019-05-07 14:41 UTC, jgvictores commented
Closed as `invalid` in favor of https://github.com/roboticslab-uc3m/teo-configuration-files/pull/21